#pragma once

#include "EnemyRestTask.h"
#include "EnemyIntimidateTask.h"
#include "EnemyWalkTask.h"
#include "EnemyTargetTurnTask.h"
#include "EnemyNearAttack0Task.h"
#include "EnemyNearAttack1Task.h"
#include "EnemyNearAttack2Task.h"
#include "EnemyNearAttack3Task.h"
#include "EnemyNearSpecialAttack0Task.h"
#include "EnemyFarAttack0Task.h"
#include "EnemyFarAttack1Task.h"
#include "EnemyFarAttack2Task.h"
#include "EnemyFarSpecialAttack0Task.h"